// Generated by gencpp from file hello_ros/led_state.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_LED_STATE_H
#define HELLO_ROS_MESSAGE_LED_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_ros
{
template <class ContainerAllocator>
struct led_state_
{
  typedef led_state_<ContainerAllocator> Type;

  led_state_()
    : led_state(0)  {
    }
  led_state_(const ContainerAllocator& _alloc)
    : led_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _led_state_type;
  _led_state_type led_state;





  typedef boost::shared_ptr< ::hello_ros::led_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::led_state_<ContainerAllocator> const> ConstPtr;

}; // struct led_state_

typedef ::hello_ros::led_state_<std::allocator<void> > led_state;

typedef boost::shared_ptr< ::hello_ros::led_state > led_statePtr;
typedef boost::shared_ptr< ::hello_ros::led_state const> led_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::led_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::led_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::led_state_<ContainerAllocator1> & lhs, const ::hello_ros::led_state_<ContainerAllocator2> & rhs)
{
  return lhs.led_state == rhs.led_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::led_state_<ContainerAllocator1> & lhs, const ::hello_ros::led_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::led_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::led_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::led_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::led_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::led_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::led_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "569a11dc0ada46c5a0c7d383fcce43c4";
  }

  static const char* value(const ::hello_ros::led_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x569a11dc0ada46c5ULL;
  static const uint64_t static_value2 = 0xa0c7d383fcce43c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/led_state";
  }

  static const char* value(const ::hello_ros::led_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::led_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 led_state\n"
;
  }

  static const char* value(const ::hello_ros::led_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::led_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct led_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::led_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::led_state_<ContainerAllocator>& v)
  {
    s << indent << "led_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_LED_STATE_H
